export const MOCK_PRODUCTS = [
  // ============ BAGS ============
  {
    _id: "101",
    name: "Crocodile Leather Birkin Style",
    description:
      "Handcrafted from genuine niloticus crocodile leather with palladium hardware. The ultimate statement of luxury and exclusivity.",
    price: 45000,
    imageUrl: "/images/products/bag1.png",
    category: "Bags",
    collectionName: "Essentials",
    stock: 2,
    isFeatured: true,
  },
  {
    _id: "102",
    name: "Calfskin Top Handle Bag",
    description:
      "Structured top handle bag in smooth box calfskin with a signature gold clasp. Minimalist, architectural, timeless.",
    price: 3200,
    imageUrl: "/images/products/bag2.png",
    category: "Bags",
    collectionName: "Essentials",
    stock: 5,
    isFeatured: false,
  },

  // ============ WATCHES & JEWELRY ============
  {
    _id: "201",
    name: "Rose Gold Tourbillon Watch",
    description:
      "A masterclass in haute horlogerie. Features an exposed tourbillon, 18k rose gold case, and hand-stitched alligator strap.",
    price: 125000,
    imageUrl: "/images/products/watch.png",
    category: "Accessories",
    collectionName: "Evening",
    stock: 1,
    isFeatured: true,
  },
  {
    _id: "202",
    name: "Diamond Tennis Necklace",
    description:
      "30 carats of internally flawless diamonds set in platinum. Designed to cascade effortlessly along the collarbone.",
    price: 85000,
    imageUrl: "/images/products/necklece.png",
    category: "Accessories",
    collectionName: "Evening",
    stock: 3,
    isFeatured: true,
  },
  {
    _id: "203",
    name: "Sapphire & Diamond Ring",
    description:
      "A spectacular 5-carat Ceylon sapphire surrounded by brilliant-cut diamonds, mounted on an 18k white gold band.",
    price: 42000,
    imageUrl: "/images/products/ring.png",
    category: "Accessories",
    collectionName: "Evening",
    stock: 1,
    isFeatured: false,
  },

  // ============ CLOTHING ============
  {
    _id: "301",
    name: "Vicuna Wool Overcoat",
    description:
      "Tailored from the rarest and finest vicuna wool. Offering unparalleled softness and warmth with a weightless feel.",
    price: 15000,
    imageUrl: "/images/products/coat.png",
    category: "Clothing",
    collectionName: "Winter",
    stock: 4,
    isFeatured: true,
  },
  {
    _id: "302",
    name: "Bespoke Tuxedo",
    description:
      "Hand-canvassed tuxedo in barathea wool with silk-satin lapels. Includes two fittings with our master tailor.",
    price: 6500,
    imageUrl: "/images/products/suit.png",
    category: "Clothing",
    collectionName: "Evening",
    stock: 8,
    isFeatured: false,
  },
  {
    _id: "303",
    name: "Silk Kimono Robe",
    description:
      "Authentic Kyoto silk kimono, hand-dyed using centuries-old Yuzen techniques. A wearable piece of art.",
    price: 4800,
    imageUrl: "/images/products/silk_robe.png",
    category: "Clothing",
    collectionName: "Resort",
    stock: 3,
    isFeatured: true,
    fit: "One Size Fits All",
  },

  // ============ SHOES ============
  {
    _id: "401",
    name: "Alligator Leather Oxfords",
    description:
      "Wholecut oxfords crafted from a single piece of premium alligator leather. Hand-painted and burnished to a deep patina.",
    price: 4200,
    imageUrl: "/images/products/shose.png",
    category: "Shoes",
    collectionName: "Essentials",
    stock: 6,
    isFeatured: true,
  },
  {
    _id: "402",
    name: "Crystal-Embellished Pumps",
    description:
      "Satin pumps adorned with hand-placed Swarovski crystals. Featuring a sleek 105mm stiletto heel.",
    price: 1850,
    imageUrl: "/images/products/heels.png",
    category: "Shoes",
    collectionName: "Evening",
    stock: 12,
    isFeatured: false,
  },

  // Add these to your MOCK_PRODUCTS array
{
  _id: "501",
  name: "Autumn Lying Cashmere Wrap",
  description: "Luxurious cashmere wrap in rich autumn tones. Hand-fringed and impossibly soft.",
  price: 2800,
  imageUrl: "/images/products/AtumnLyring.png",
  category: "Clothing",
  collectionName: "AutumnLying",
  stock: 5,
  isFeatured: false,
},
{
  _id: "502",
  name: "Evening Silk Gown",
  description: "Floor-length silk charmeuse gown with a plunging back. Available in custom measurements.",
  price: 5600,
  imageUrl: "/images/products/EveningSilk.png",
  category: "Clothing",
  collectionName: "EveningSilk",
  stock: 3,
  isFeatured: true,
},
{
  _id: "503",
  name: "Linen Blend Suit",
  description: "Lightweight linen suit in a breathable blend, ideal for resort or summer events.",
  price: 3900,
  imageUrl: "/images/products/Linen.png",
  category: "Clothing",
  collectionName: "Linen",
  stock: 8,
  isFeatured: false,
},
{
  _id: "504",
  name: "Resort Paints Pareo",
  description: "Hand-painted silk pareo in vibrant resort prints. Each piece is unique.",
  price: 1200,
  imageUrl: "/images/products/ResortPaints.png",
  category: "Accessories",
  collectionName: "ResortPaints",
  stock: 15,
  isFeatured: false,
},
{
  _id: "505",
  name: "Winter Down Puffer",
  description: "Ultra-lightweight down jacket, ethically sourced and packed with 800-fill goose down.",
  price: 2200,
  imageUrl: "/images/products/WinteDown.png",
  category: "Clothing",
  collectionName: "WinterDown",
  stock: 6,
  isFeatured: true,
},
];