export const MOCK_PRODUCTS = [
  {
    _id: "1",
    name: "Classic Leather Tote",
    description: "A timeless leather tote for everyday elegance. Handcrafted from full-grain Italian leather with reinforced stitching and brushed gold hardware.",
    price: 450,
    imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&h=1000&fit=crop",
    category: "Bags",
    collectionName: "Essentials",
    stock: 10,
    isFeatured: true,
  },
  {
    _id: "2",
    name: "Silk Evening Scarf",
    description: "100% pure silk scarf with hand-rolled edges. A statement of understated luxury for any occasion.",
    price: 120,
    imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&h=1000&fit=crop",
    category: "Accessories",
    collectionName: "Evening",
    stock: 25,
    isFeatured: true,
  },
  {
    _id: "3",
    name: "Minimalist Gold Watch",
    description: "Swiss-made minimalist watch with 18k gold plated mesh band. The essence of timeless precision.",
    price: 290,
    imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&h=1000&fit=crop",
    category: "Accessories",
    collectionName: "Essentials",
    stock: 5,
    isFeatured: false,
  },
  {
    _id: "4",
    name: "Cashmere Turtleneck",
    description: "Ultra-soft sustainably sourced cashmere sweater. Woven by artisan craftsmen in Mongolia for unparalleled warmth.",
    price: 350,
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800&h=1000&fit=crop",
    category: "Clothing",
    collectionName: "Winter",
    stock: 15,
    isFeatured: true,
  },
  {
    _id: "5",
    name: "Wool Overcoat",
    description: "Double-breasted wool overcoat in charcoal. Cut from heavyweight Italian wool with a silk-blend lining for exceptional drape.",
    price: 890,
    imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&h=1000&fit=crop",
    category: "Clothing",
    collectionName: "Winter",
    stock: 8,
    isFeatured: true,
  },
  {
    _id: "6",
    name: "Leather Crossbody",
    description: "Compact crossbody bag in vegetable-tanned leather. Designed for modern mobility without compromising on style.",
    price: 320,
    imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=1000&fit=crop",
    category: "Bags",
    collectionName: "Essentials",
    stock: 12,
    isFeatured: false,
  },
  {
    _id: "7",
    name: "Linen Blazer",
    description: "Relaxed-fit linen blazer in natural ecru. Perfect for warm evenings, crafted from Belgian linen with mother-of-pearl buttons.",
    price: 520,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop",
    category: "Clothing",
    collectionName: "Evening",
    stock: 6,
    isFeatured: true,
  },
  {
    _id: "8",
    name: "Pearl Drop Earrings",
    description: "Freshwater pearl earrings set in sterling silver. Each pearl is individually selected for its natural luminescence.",
    price: 180,
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&h=1000&fit=crop",
    category: "Accessories",
    collectionName: "Evening",
    stock: 20,
    isFeatured: false,
  },
];