export const MOCK_PRODUCTS = [
  {
    _id: "1",
    name: "Classic Leather Tote",
    description: "A timeless leather tote for everyday elegance.",
    price: 450,
    imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=2000&auto=format&fit=crop",
    category: "Bags",
    collectionName: "Essentials",
    stock: 10,
    isFeatured: true,
  },
  {
    _id: "2",
    name: "Silk Evening Scarf",
    description: "100% pure silk scarf with hand-rolled edges.",
    price: 120,
    imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=2000&auto=format&fit=crop",
    category: "Accessories",
    collectionName: "Evening",
    stock: 25,
    isFeatured: true,
  },
  {
    _id: "3",
    name: "Minimalist Gold Watch",
    description: "Swiss-made minimalist watch with a 18k gold plated mesh band.",
    price: 290,
    imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=2000&auto=format&fit=crop",
    category: "Accessories",
    collectionName: "Essentials",
    stock: 5,
    isFeatured: false,
  },
  {
    _id: "4",
    name: "Cashmere Turtleneck",
    description: "Ultra-soft sustainably sourced cashmere sweater.",
    price: 350,
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?q=80&w=2000&auto=format&fit=crop",
    category: "Clothing",
    collectionName: "Winter",
    stock: 15,
    isFeatured: true,
  }
];
